apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myresources.mygroup.example.com
spec:
  group: mygroup.example.com
  names:
    kind: MyResource
    plural: myresources
    singular: myresource
    shortNames:
      - myres
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # spec 아래에 뭐가 오든 일단 허용 (처음엔 대충)
              x-kubernetes-preserve-unknown-fields: true
